# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e8f452dfa56094ac080d371d8b901f145f070451719be3745ca95e8c1a331743e59357474421434b561e10717035054fc58c8f2dc5d8e07dff684b166c7efbe

test:
  secret_key_base: 154b99639d8f4496cf243c67d47691766cf4071f76e736b5822516448bbfb4cd2a7c7274cdf8e4ba6a8e31623de65f78456898b83e93eedaaf8ec61730b916b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
