---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3900072693-uT8iNlhVhaLgNDXXItpcRjlKEI4Patmlr2tEX9p
:access_token_secret: P1rZp8wXengfKZLT43KmG65MlYUaeMPPI1wUX2OhMtIU0
